spring:
  data:
    mongodb:
      username: anirudh
      password: anirudh
      host: localhost
      port: 27017
      authentication-database: admin
      database: customer

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:dev.anirudh.ecommerce.kafka.OrderConfirmation,paymentConfirmation:dev.anirudh.ecommerce.notification.PaymentNotificationRequest
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port: 8040